# Test Autograd with Tensors

In [1]:
%load_ext autoreload

In [37]:
%autoreload 2

In [198]:
import numpy as np

from autodiff.tensor import Tensor

In [379]:
# base tensors
a = Tensor([1, 2, 3, 4, 5], autograd=True)
b = Tensor([2, 2, 2, 2, 2], autograd=True)
c = Tensor([5, 4, 3, 2, 1], autograd=True)

In [380]:
a, b, c

(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 2]), array([5, 4, 3, 2, 1]))

In [381]:
# composite operations
d = a + b
e = b + c
f = d + e

In [382]:
d, e, f

(array([3, 4, 5, 6, 7]), array([7, 6, 5, 4, 3]), array([10, 10, 10, 10, 10]))

In [383]:
# f.backward(Tensor([1, 1, 1, 1, 1]))
f.backward()

In [384]:
a.grad.data

array([1, 1, 1, 1, 1])

In [385]:
b.grad.data

array([2, 2, 2, 2, 2])

In [261]:
a.gra