# Test Autograd with Tensors

In [5]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
%autoreload 2

In [15]:
import numpy as np

from autodiff.tensor import Tensor

## case 1

In [32]:
# base tensors
a = Tensor([1, 2, 3, 4, 5], autograd=True)
b = Tensor([2, 2, 2, 2, 2], autograd=True)
c = Tensor([5, 4, 3, 2, 1], autograd=True)

In [33]:
a, b, c

(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 2]), array([5, 4, 3, 2, 1]))

In [34]:
# composite operations
d = a + b
e = b + c
f = d + e

In [35]:
d, e, f

(array([3, 4, 5, 6, 7]), array([7, 6, 5, 4, 3]), array([10, 10, 10, 10, 10]))

In [36]:
# f.backward(Tensor([1, 1, 1, 1, 1]))
f.backward()

In [37]:
a.grad.data

array([1, 1, 1, 1, 1])

In [38]:
b.grad.data

array([2, 2, 2, 2, 2])

## case 2

In [39]:
# base tensors
a = Tensor([1, 2, 3, 4, 5], autograd=True)
b = Tensor([2, 2, 2, 2, 2], autograd=True)
c = Tensor([5, 4, 3, 2, 1], autograd=True)

In [40]:
a, b, c

(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 2]), array([5, 4, 3, 2, 1]))

In [41]:
# composite operations
d = a + -b
e = -b + c
f = d + e

In [42]:
d, e, f

(array([-1,  0,  1,  2,  3]),
 array([ 3,  2,  1,  0, -1]),
 array([2, 2, 2, 2, 2]))

In [43]:
# f.backward(Tensor([1, 1, 1, 1, 1]))
f.backward()

In [44]:
a.grad.data

array([1, 1, 1, 1, 1])

In [45]:
b.grad.data

array([-2, -2, -2, -2, -2])

# Neural Network

In [46]:
np.random.seed(3301)

In [48]:
data = Tensor(np.array([[0, 0], [0, 1], [1, 0], [1, 1]]), autograd=True)
target = Tensor(np.array([[0], [1], [0], [1]]), autograd=True)

In [49]:
w = []
w.append(Tensor(np.random.rand(2, 3), autograd=True))
w.append(Tensor(np.random.rand(3, 1), autograd=True))

In [ ]:
for i in range(10):
    pred = data.mm(w[0]).mm(w[1])

    loss ((pred - target)*(pred - target)).sum(0)

    loss.ackward(Tensor(np.ones_like(loss.data)))
    for w_ in w:
        w_.data -= w_.grad.data * 0.1
        w_.data *= 0

    print(loss)