In [142]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [505]:
import autodiff.reverse_mode as rm
import autodiff.elemental_functions as f
import numpy as np

In [504]:
%autoreload now

In [507]:
x1 = rm.Variable(2)
x2 = rm.Variable(3)

z3 = f.multiply(x1, x2)

y = f.log(z3)
y.grad()

In [509]:
z3.adjoints

[(<autodiff.reverse_mode.Variable at 0x7fce788c4c70>, 3),
 (<autodiff.reverse_mode.Variable at 0x7fce788c5b70>, 2)]

In [510]:
x1.gradient, x2.gradient

(0.5, 0.3333333333333333)

## example 2 (paper)

In [511]:
x1 = rm.Variable(2)
x2 = rm.Variable(5)

In [513]:
# forward prop
v1 = f.log(x1)
v2 = f.multiply(x1, x2)
v3 = f.sin(x2)

print(v1.value, v2.value, v3.value)

0.6931471805599453 10 -0.9589242746631385


In [514]:
v4 = f.add(v1, v2)
y = f.subtract(v4, v3)

print(v4.value, y.value)

10.693147180559945 11.652071455223084


In [515]:
y.grad()

In [516]:
v4.gradient

1.0

In [517]:
v3.gradient

-1.0

In [518]:
v1.gradient

1.0

In [519]:
v2.gradient

1.0

In [520]:
x1.gradient

5.5

In [521]:
x2.gradient

1.7163378145367738

# with arrays

In [522]:
x1 = rm.Variable(np.array([1, 2, 3]))
x2 = rm.Variable(np.array([2, 5, 4]))

In [524]:
# forward prop
v1 = f.log(x1)
v2 = f.multiply(x1, x2)
v3 = f.sin(x2)

print(v1.value, v2.value, v3.value)

[0.         0.69314718 1.09861229] [ 2 10 12] [ 0.90929743 -0.95892427 -0.7568025 ]


In [525]:
v4 = f.add(v1, v2)
y = f.subtract(v4, v3)

print(v4.value, y.value)

[ 2.         10.69314718 13.09861229] [ 1.09070257 11.65207146 13.85541478]


In [526]:
y.grad()

In [527]:
x1.gradient

array([3.        , 5.5       , 4.33333333])

In [ ]:
x2.gradient